name: Build and Deploy

on: [push] # è§¦å‘æ¡ä»¶(git æ¨é€æ—¶)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸	# è·å–æºç 
        uses: actions/checkout@v2 # ä¸‹é¢è¿™ä¸ªæœ€å¥½è®¾æˆ false
        with:
          persist-credentials: false
      - name: Install ğŸ”§ and Build  ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3 # æ„å»ºå’Œéƒ¨ç½²
        run: |
          docker start gitbook-html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: docs # æƒ³éƒ¨ç½²çš„æ–‡ä»¶å¤¹
